name: Dump GH Contexts for PR Actions

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  tmp:
    runs-on: ubuntu-latest
    steps:
      - name: "git clone"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "git log"
        run: git log
      - name: "github-script"
        uses: actions/github-script@v6
        with:
          script: |
            if (context.eventName === 'pull_request') {
              console.log(`PR - number ${context.payload.number}`);
              if (context.payload.action === 'opened') {
                console.log(`PR - new PR opened, HEAD is ${context.payload.pull_request.head.sha}`);
              } else if (context.payload.action === 'synchronize') {
                console.log(`PR - new commits pushed, HEAD is ${context.payload.after}`);
              }
            }
