name: Dump GH Contexts for PR Actions

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  tmp:
    runs-on: ubuntu-latest
    steps:
      - name: "git clone"
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: "github-script"
        uses: actions/github-script@v6
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
        with:
          github-token: ${{ secrets.COMMENTING_GITHUB_TOKEN }}
          script: |
            if (context.eventName === 'pull_request') {
              let text = '';
              if (context.payload.action === 'opened') {
                text = `Thank you for submitting a PR starting from \`${context.payload.pull_request.head.sha}\`.`;
              } else if (context.payload.action === 'synchronize') {
                text = `Thank you for submitting commit \`${context.payload.after}\`.`;
              }
              if (text !== '') {
                await github.rest.issues.createComment({
                  issue_number: context.payload.number,
                  repo: context.payload.pull_request.base.repo.name,
                  owner: process.env.GITHUB_REPOSITORY_OWNER,
                  body: text
                });
              }
            }
